name: Deployment Tests

on:
  workflow_run:
    workflows: ["Docker Image CI"]  # Replace this with the exact name of your CI workflow if different
    types:
      - completed
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test_api.py
        run: python tests/test_API.py

      - name: Run test_failure.py
        run: python tests/test_failure.py

      - name: Run test_load.py
        run: python tests/test_load.py

