name: Deployment Tests

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI or API

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run test_api.py
        run: python tests/test_API.py

      - name: Run test_failure.py
        run: python tests/test_failure.py

      - name: Run test_load.py
        run: python tests/test_load.py

